name: Code Review Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置环境变量
      - name: Set environment variables
        run: echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> $GITHUB_ENV

      # 暂存所有更改
      - name: Stage changes
        run: git add .

      # 运行 Shell 脚本，执行代码差异获取和 API 调用
      - name: Run Code Review Script
        run: |
          chmod +x scripts/code_review.sh
          ./scripts/code_review.sh

      # 上传生成的 Markdown 文件
      - name: Upload Markdown Review Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-result
          path: codeReviewLog/codeReviewResult_*.md
