name: Code Review Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装 jq 以便处理 JSON 响应
      - name: Install jq
        run: sudo apt-get install jq

      # 设置 API_KEY_SECRET 环境变量
      - name: Set environment variables
        run: echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> $GITHUB_ENV

      # 暂存所有更改
      - name: Stage changes
        run: git add .

      # 确保脚本有执行权限
      - name: Make script executable
        run: chmod +x scripts/code_review.sh

      # 运行代码审查脚本
      - name: Run Code Review Script
        run: ./scripts/code_review.sh

      # 上传生成的 Markdown 文件
      - name: Upload Markdown Review Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-result
          path: codeReviewLog/codeReviewResult_*.md
