name: Code Review Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 API 密钥环境变量
      - name: Set environment variables
        env:
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}

      # 获取代码差异和提交信息
      - name: Get changes and commit info
        id: get_changes
        run: |
          commitHash=$(git rev-parse HEAD)
          author=$(git log -1 --pretty=format:'%an <%ae>')

          if git rev-parse --quiet --verify HEAD~1; then
            changes=$(git diff HEAD~1 HEAD)
          else
            changes=$(git diff)
          fi

          echo "commit_hash=$commitHash" >> $GITHUB_ENV
          echo "author=$author" >> $GITHUB_ENV
          echo "changes=$changes" >> $GITHUB_ENV

      # 运行代码审查脚本
      - name: Run Code Review Script
        run: |
          chmod +x scripts/code_review.sh  # 确保脚本有执行权限
          ./scripts/code_review.sh "${{ env.changes }}"  # 传递代码差异作为参数

      # 上传生成的 Markdown 结果
      - name: Upload Markdown Review Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-result
          path: codeReviewLog/codeReviewResult_*.md
