name: Code Review Automation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set environment variables
        run: echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> $GITHUB_ENV

      - name: Stage changes
        run: git add .

      - name: Print commit info
        run: |
          echo "Latest commit hash:"
          git rev-parse HEAD
          echo "Previous commit hash:"
          git rev-parse HEAD~1
          echo "Git changes:"
          git diff HEAD~1 HEAD

      - name: Ensure script is executable
        run: chmod +x ./scripts/code_review.sh

      - name: Run Code Review Script
        run: ./scripts/code_review.sh

      - name: List codeReviewLog directory
        run: |
          echo "Listing files in codeReviewLog directory:"
          ls -la codeReviewLog

      - name: Check review result file
        run: |
          if [ -f "codeReviewLog/codeReviewResult_*.md" ]; then
            echo "Review result file found."
          else
            echo "Review result file not found!"
            exit 1
          fi

      - name: Upload Markdown Review Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-result
          path: codeReviewLog/codeReviewResult_*.md
