name: Code Review Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本

    steps:
      # 第一步，检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 API 密钥环境变量
      - name: Set environment variables
        run: echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> $GITHUB_ENV

      # 自动暂存所有改动，这样 git diff --cached 可以检测到更改
      - name: Stage all changes
        run: git add .

      # 运行代码审查脚本
      - name: Run Code Review Script
        run: |
          chmod +x scripts/code_review.sh  # 确保脚本有执行权限
          ./scripts/code_review.sh          # 运行代码审查脚本

      # 上传生成的 Markdown 结果
      - name: Upload Markdown Review Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-result
          path: codeReviewLog/codeReviewResult_*.md
